apiVersion: v1
kind: PersistentVolume 
metadata:
name: pv-vol1 
spec:
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  awsElasticBlockStore: 
  volumeID: <volume-id> 
  fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: myclaim 
spec:
  accessModes:
     - ReadWriteOnce
  resources:
     requests:
storage: 500Mi